---
- name: Check Interfaces
  hosts: all
  gather_facts: false
  connection: local

  vars:
      cli:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_ssh_pass }}"

  tasks:

    - name: show ip interfarce brief
      ios_command:
          commands: show ip interface brief
          provider: "{{ cli }}"
      register: output

    - name: show output
      debug:
          var: output

    - name: copy output to file
      copy: content="{{ output }}" dest=./output/{{ inventory_hostname }}.txt

...
