---
- name: Create Loopback IP Addresses for R1, R2, and S1
  hosts: all
  gather_facts: false
  connection: network_cli

- name: Create Loopback for R1
  hosts: R1
  gather_facts: false
  connection: network_cli

  tasks:

    - name: Interface Loopback2
      ios_config:
        lines:
            - ip address 12.12.12.12 255.255.255.255
        parents: interface loopback 2

    - name: Verification
      ios_command:
          commands:
            - show run interface loopback 2
      register: output

    - name: Display output
      debug:
        var: output

    - name: Delete Loopback interface
      ios_interface:
          name: Loopback2
          state: absent

- name: Create Loopback for R2
  hosts: R2
  gather_facts: false
  connection: network_cli

  tasks:

    - name: Interface Loopback2
      ios_config:
        parents: interface loopback 2
        lines:
            - ip address 13.13.13.13 255.255.255.255

    - name: Verification
      ios_command:
          commands:
            - show run interface loopback 2
      register: output

    - name: Display output
      debug:
        var: output

    - name: Delete Loopback interface
      ios_interface:
          name: Loopback2
          state: absent

- name: Create Loopback for S1
  hosts: S1
  gather_facts: false
  connection: network_cli

  tasks:

    - name: Interface Loopback2
      ios_config:
        parents: interface loopback 2
        lines:
            - ip address 14.14.14.14 255.255.255.255

    - name: Verification
      ios_command:
          commands:
            - show run interface loopback 2
      register: output

    - name: Display output
      debug:
        var: output

    - name: Delete Loopback interface
      ios_interface:
          name: Loopback2
          state: absent
